#!/usr/bin/env ruby
require 'thor'
require './libs/os'
require './libs/tackle_environment'

TACKLE_ENVIRONMENT = TackleEnvironment.build(OS.get)

class TackleCLI < Thor
  desc 'up', 'runs Consul, Registrator and Docker Compose for projects in tackle.yml'
  def up
    TACKLE_ENVIRONMENT.verify_environment
    TACKLE_ENVIRONMENT.verify_consul_running
    TACKLE_ENVIRONMENT.run_projects
    TACKLE_ENVIRONMENT.print_consul_uri
  end

  desc 'down', 'stops Consul, Registrator and Docker Compose for projects in tackle.yml'
  def down
    TACKLE_ENVIRONMENT.verify_environment
    TACKLE_ENVIRONMENT.stop_consul
    TACKLE_ENVIRONMENT.stop_projects
  end

  desc 'setup', 'run setup steps for projects in tackle.yml'
  def setup
    TACKLE_ENVIRONMENT.verify_environment
    TACKLE_ENVIRONMENT.setup_projects
  end

  desc 'install', 'install Docker and Docker Compose'
  def install
    system('ansible-playbook ./ansible/install.yml -i 127.0.0.1, --ask-sudo-pass --verbose')
  end
end

TackleCLI.start(ARGV)