---
- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Update Homebrew
      homebrew: update_homebrew=yes

    - name: Tap Caskroom
      homebrew_tap: tap=caskroom/cask

    - name: Install Caskroom
      homebrew: name=brew-cask state=latest

    - name: Install Virtualbox
      homebrew_cask: name=virtualbox state=present
      environment:
        HOMEBREW_CASK_OPTS: --appdir=/Applications

    - name: Install Docker and Extras
      homebrew:
        name: "{{ item }}"
        state: latest
      with_items:
        - docker
        - docker-machine
        - docker-compose

    - name: Add NFS share to /etc/exports
      blockinfile:
        dest: /etc/exports
        create: yes
        marker: "## {mark} Tackle Developer Environment - ANSIBLE MANAGED BLOCK ##"
        content: '/Users 192.168.99.100 -alldirs -mapall=0:80'
      become: yes
      become_method: sudo
      register: exports

    - name: Restart nfsd
      command: sudo nfsd restart
      become: yes
      become_method: sudo
      when: exports.changed