---
- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Add NFS share to /etc/exports
      blockinfile:
        dest: /etc/exports
        create: yes
        marker: "## {mark} Tackle Developer Environment - ANSIBLE MANAGED BLOCK ##"
        content: '/Users {{ docker_machine_ip }} -alldirs -mapall=0:80'
      become: yes
      become_method: sudo
      register: exports

    - name: Restart nfsd
      command: sudo nfsd restart
      become: yes
      become_method: sudo
      when: exports.changed