---
- hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Install Docker
    apt: name=docker-engine update_cache=yes
    sudo: yes

  - name: Enable Docker for non sudo users
    shell: usermod -aG docker {{ ansible_user_id }}
    sudo: yes

  - name: Start Docker service
    service: name=docker state=started
    sudo: yes

  - name: Install Docker Compose 1.7.0
    shell: curl -L https://github.com/docker/compose/releases/download/1.7.0-rc1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
    sudo: yes

  - name: Add executable to Docker Compose
    shell: chmod +x /usr/local/bin/docker-compose
    sudo: yes